language: go

sudo: false

os:
  - linux
  - osx

go:
  - 1.8.7
  - 1.9.4

install:
  - go get -t ./...
  - go get -u github.com/mdempsky/unconvert
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - go test -v ./...
  - unconvert $(go list ./... | grep -v /vendor/)
  - find . ! \( -path './vendor' -prune \) -type f -name '*.go' -print0 | xargs -0 gofmt -l -s
  - golint ./...
